# Generated by Django 2.2.4 on 2023-06-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
