# Generated by Django 2.2.4 on 2023-06-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueApi', '0002_auto_20230607_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictions',
            name='employed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married')], max_length=50),
        ),
    ]
