# Generated by Django 2.2.4 on 2023-06-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueApi', '0003_auto_20230607_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictions',
            old_name='graduated',
            new_name='Education_Status',
        ),
    ]
